"""
Summary domain models — the structured output of the summarisation pipeline.

These live in the domain layer, not inside the summarisation package, because
the deterministic extraction stage produces them too. Keeping them here is what
lets extraction and summarisation share a vocabulary without importing each
other.
"""

from __future__ import annotations

from datetime import datetime
from typing import List

from pydantic import BaseModel, Field


class SourceReference(BaseModel):
    """
    Where a summary statement came from.

    Page numbers are carried through from the canonical chunks and are never
    generated by a model, so a citation cannot be fabricated.
    """

    chunk_ids: List[str] = Field(default_factory=list)
    page_start: int = 1
    page_end: int = 1
    section_title: str = ""
    section_number: str = ""

    @property
    def page_label(self) -> str:
        if self.page_start == self.page_end:
            return f"Page {self.page_start}"
        return f"Pages {self.page_start}-{self.page_end}"


class SummaryItem(BaseModel):
    """One structured finding, with its own provenance."""

    type: str = ""
    label: str = ""
    summary: str = ""
    value: str = ""
    source_pages: List[int] = Field(default_factory=list)
    section_title: str = ""


class SectionSummary(BaseModel):
    """A summary of one section of the document."""

    section_id: str = ""
    section_number: str = ""
    section_title: str = ""
    summary: str = ""
    key_points: List[str] = Field(default_factory=list)
    page_start: int = 1
    page_end: int = 1
    chunk_ids: List[str] = Field(default_factory=list)

    @property
    def page_label(self) -> str:
        if self.page_start == self.page_end:
            return f"Page {self.page_start}"
        return f"Pages {self.page_start}-{self.page_end}"

    @property
    def section_label(self) -> str:
        """Citation label, e.g. '5.4 Termination'."""
        if self.section_number and self.section_title:
            return f"{self.section_number} {self.section_title}"
        return (self.section_number or self.section_title or "").strip()


class SummaryResult(BaseModel):
    """
    The complete structured summary of one document.

    Deliberately not one large paragraph: narrative prose comes from the
    summarisation model, while `parties`, `key_dates` and `financial_terms` come
    from deterministic extraction over the canonical chunks. That split is what
    lets the structured output exist without any LLM, and it is also why those
    fields carry exact page references.

    Risk is not represented here. Flagging something as legally dangerous is a
    separate analysis feature; a summary that invents risk is worse than no risk
    assessment at all.
    """

    document_id: str

    document_overview: str = ""
    document_type: str = ""
    executive_summary: str = ""

    parties: List[SummaryItem] = Field(default_factory=list)
    key_dates: List[SummaryItem] = Field(default_factory=list)
    financial_terms: List[SummaryItem] = Field(default_factory=list)
    key_obligations: List[SummaryItem] = Field(default_factory=list)
    important_clauses: List[SummaryItem] = Field(default_factory=list)
    attention_points: List[SummaryItem] = Field(default_factory=list)

    section_summaries: List[SectionSummary] = Field(default_factory=list)
    source_references: List[SourceReference] = Field(default_factory=list)

    # Provenance — which engine produced this, so a stored summary stays
    # attributable after the model is changed.
    provider: str = ""
    model_name: str = ""
    model_version: str = ""
    pipeline_version: str = ""
    prompt_version: str = ""
    processing_time: float = 0.0
    created_at: datetime = Field(default_factory=datetime.utcnow)

    # Set when summarisation degraded — e.g. the model could not be loaded.
    degraded: bool = False
    degraded_reason: str = ""
